
version: '2.2'

services:

  mapper_client:
    build:
      context: test_client
    user: nobody:nogroup
    image: cyberdojo/mapper-client
    init: true
    container_name: test-mapper-client
    ports: [4548:4548]
    read_only: true
    tmpfs: /tmp
    restart: 'no'
    depends_on:
      - mapper

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  mapper:
    build:
      context: .
      args:
        - SHA
    user: nobody
    image: cyberdojo/mapper
    init: true
    container_name: test-mapper-server
    read_only: true
    ports: [4547:4547]
    tmpfs: /tmp
    restart: 'no'
    volumes:
      - ./test_server:/app/test:ro
      - ./test_server/data/porter:/porter:ro
