version: 2
jobs:
  build-publish-image:

    machine:
      enabled: true

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            set -ev
            ./pipe_build_up_test.sh
      - run:
          name: push docker image to dockerhub
          command: |
            set -ev
            readonly project=${CIRCLE_PROJECT_REPONAME}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker tag  cyberdojo/${project}:latest cyberdojo/${project}:beta
            echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
            docker push cyberdojo/${project}:${CIRCLE_SHA1:0:7}
            docker push cyberdojo/${project}:beta

  deploy-image-to-beta:
    docker:
      - image: cyberdojo/gcloud-kubectl-helm
    steps:
      - run:
          name: authenticate with gcloud and deploy with helm
          command: |
            set -o errexit
            echo $GCP_K8S_CREDENTIALS > /gcp/gcp-credentials.json
            gcloud auth activate-service-account "$SERVICE_ACCOUNT" --key-file=/gcp/gcp-credentials.json
            gcloud container clusters get-credentials "$CLUSTER" --zone "$ZONE" --project "$PROJECT"
            helm init --client-only
            helm repo add praqma https://praqma-helm-repo.s3.amazonaws.com/
            helm upgrade --install --reuse-values --namespace=beta --set-string image.mapper.tag=${CIRCLE_SHA1:0:7} beta-cyber-dojo praqma/cyber-dojo
            #helm upgrade --install --namespace=beta --set-string image.mapper.tag=${CIRCLE_SHA1:0:7} beta-cyber-dojo praqma/cyber-dojo

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish-image:
          context: cyberdojo-context
          filters:
            branches:
              only:
                  - master
      - deploy-image-to-beta:
          context: cyberdojo-context
          requires:
            - build-publish-image
