# Default values for cyber-dojo-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

fullnameOverride: "mapper"

replicaCount: 1

service:
  port: 4547

volumes:
  - name: mapper-tmp-dir
    emptyDir: {}
  - name: mapper-data
    persistentVolumeClaim:
      claimName: mapper-data

containers:
  - name: mapper
    image: cyberdojo/mapper
    securityContext:
      runAsUser: 65534
      fsGroup: 65533
    volumeMounts:
      - name: mapper-tmp-dir
        mountPath: /tmp
        readOnly: false
      - name: mapper-data
        mountPath: /porter
    resources:
      limits:
        memory: 32Mi
      requests:
        memory: 32Mi
      livenessProbe:
        path: /sha
        port: 4547
      readinessProbe:
        path: /ready?
        port: 4547

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
